### ISSUE TITLE
Mongo to pandas

### ISSUE THREAD

**Issue by michaelaye** [ContinuumIO/odo#160]
If I understand the docs this should be working:

```python
odo('mongodb://localhost:27017/planet_four::planet_four_subjects',
    'hdfstore://Users/klay6683/data/planet4/2015-03-31.h5::/df')
```
I also tried removing the / in front of df:

```python
odo('mongodb://localhost:27017/planet_four::planet_four_subjects',
    'hdfstore://Users/klay6683/data/planet4/2015-03-31.h5::df')
```
and without a path:
```python
odo('mongodb://localhost:27017/planet_four::planet_four_subjects',
    'hdfstore://Users/klay6683/data/planet4/2015-03-31.h5')
```
and also tried using '.hdf5' as extension. 
I always get this error:

```python
/Users/klay6683/miniconda3/lib/python3.4/site-packages/datashape/discovery.py in discover(o, **kwargs)
     51         return from_numpy(o.shape, o.dtype)
     52     raise NotImplementedError("Don't know how to discover type %r" %
---> 53                               type(o).__name__)
     54 
     55 

NotImplementedError: Don't know how to discover type 'ObjectId'
```

System: Python 3.4, via conda on a Mac
$ conda list odo
# packages in environment at /Users/klay6683/miniconda3:
#
odo                       0.3.1                np19py34_0

**Comment by mrocklin** [comment]
Your collection holds ObjectIds in a field that is not named _id.  This is
slightly atypical but something to which odo should probably be robust.
Discover on mongo collections should probably look for this case and ignore
that column.

**Comment by michaelaye** [comment]
I don't know really anything about Mongo (hence trying to get to HDF), so I might be out of my waters here, but:
```python
subjects.find_one().keys()

dict_keys(['state', 'project_id', 'classification_count', 'zooniverse_id', 'created_at', '_id', 'location', 'updated_at', 'workflow_ids', 'random', 'activated_at', 'metadata', 'coords'])
```
at least I see an '_id' there in the keys?

**Comment by mrocklin** [comment]
Mongo stores keys as type ObjectId.  Normally Odo tries to filter these out
before migrating to other formats.  Currently it only checks the _id
field.  If you have ObjectIds in other fields then it has problems.

Actually, that's not true, it looks like we've fixed this in diiscover
https://github.com/ContinuumIO/odo/blob/master/odo/backends/mongo.py#L18-L31
But we haven't yet copied that fix over to Collection -> Iterator
https://github.com/ContinuumIO/odo/blob/master/odo/backends/mongo.py#L34-L47

**Comment by mrocklin** [comment]
As always, contributions welcome.

**Comment by michaelaye** [comment]
Sorry, that is all spanish to me, I would not know where to start.
* is `ds = discover(items)` the line that solves it in discover_pymongo_collection?
* i don't understand the relationship between _into_iter_mongodb and discover_pymongo_collection

**Comment by michaelaye** [comment]
Weird: I tried the first lines of 
https://github.com/ContinuumIO/odo/blob/master/odo/backends/mongo.py#L18-L31
and they still fail at the `discover` step:

```python
items = list(take(1, subjects.find()))
oid_cols = [k for k,v in items[0].items() if isinstance(v, ObjectId)]
print("OID_cols:\n",oid_cols)
item = items[0]
for col in oid_cols:
    del item[col]
print('items[0].keys():\n',items[0].keys())
discover(items)

OID_cols:
 ['project_id', '_id']
items[0].keys():
 dict_keys(['created_at', 'zooniverse_id', 'activated_at', 'workflow_ids', 'state', 'metadata', 'coords', 'classification_count', 'random', 'updated_at', 'location'])
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-41-a604cb9ba990> in <module>()
      6     del item[col]
      7 print('items[0].keys():\n',items[0].keys())
----> 8 discover(items)

/Users/klay6683/miniconda3/lib/python3.4/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    161             self._cache[types] = func
    162         try:
--> 163             return func(*args, **kwargs)
    164 
    165         except MDNotImplementedError:

/Users/klay6683/miniconda3/lib/python3.4/site-packages/datashape/discovery.py in discover(seq)
    188         try:
    189             types = [unite([discover(data) for data in column]).subshape[0]
--> 190                                            for column in columns]
    191             return len(seq) * Record(list(zip(keys, types)))
    192         except AttributeError:

/Users/klay6683/miniconda3/lib/python3.4/site-packages/datashape/discovery.py in <listcomp>(.0)
    188         try:
    189             types = [unite([discover(data) for data in column]).subshape[0]
--> 190                                            for column in columns]
    191             return len(seq) * Record(list(zip(keys, types)))
    192         except AttributeError:

/Users/klay6683/miniconda3/lib/python3.4/site-packages/datashape/discovery.py in <listcomp>(.0)
    187         columns = [[item.get(key) for item in seq] for key in keys]
    188         try:
--> 189             types = [unite([discover(data) for data in column]).subshape[0]
    190                                            for column in columns]
    191             return len(seq) * Record(list(zip(keys, types)))

/Users/klay6683/miniconda3/lib/python3.4/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    161             self._cache[types] = func
    162         try:
--> 163             return func(*args, **kwargs)
    164 
    165         except MDNotImplementedError:

/Users/klay6683/miniconda3/lib/python3.4/site-packages/datashape/discovery.py in discover(seq)
    193             pass
    194 
--> 195     types = list(map(discover, seq))
    196     return do_one([unite_identical, unite_merge_dimensions, Tuple])(types)
    197 

/Users/klay6683/miniconda3/lib/python3.4/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    161             self._cache[types] = func
    162         try:
--> 163             return func(*args, **kwargs)
    164 
    165         except MDNotImplementedError:

/Users/klay6683/miniconda3/lib/python3.4/site-packages/datashape/discovery.py in discover(o, **kwargs)
     51         return from_numpy(o.shape, o.dtype)
     52     raise NotImplementedError("Don't know how to discover type %r" %
---> 53                               type(o).__name__)
     54 
     55 

NotImplementedError: Don't know how to discover type 'ObjectId'
```

**Comment by cpcloud** [comment]
@michaelaye @mrocklin i can't reproduce this error anymore, closing
